stof_doctrine_extensions:
    default_locale: ru
    translation_fallback: true
    persist_default_translation: true
    orm:
        default:
            tree: true
            translatable: true
            sluggable: true